const ADD_TASK          = 'ADD_TASK'
const DELETE_TASK       = 'DELETE_TASK'
const CHANGE_TASK_NAME  = 'CHANGE_TASK_NAME'
const RESUME_TASK       = 'RESUME_TASK'

const CHANGE_TASK_NAME_INPUT    = 'CHANGE_TASK_NAME_INPUT'
const CHANGE_TASK_PRICE_INPUT   = 'CHANGE_TASK_PRICE_INPUT'
const RESET_INPUT_AND_TIMER     = 'RESET_INPUT_AND_TIMER'
const TICK_TIMER                = 'TICK_TIMER'

export {
  ADD_TASK,
  DELETE_TASK,
  CHANGE_TASK_NAME,
  RESUME_TASK,

  CHANGE_TASK_NAME_INPUT,
  CHANGE_TASK_PRICE_INPUT,
  RESET_INPUT_AND_TIMER,
  TICK_TIMER
}